spring:
  redis:
    database: 0
    host: 192.168.3.30
    port: 6379
    timeout: 6000
    jedis: 
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5